import jsPDF from "jspdf";
import html2canvas from "html2canvas";

// ── Color Palette ─────────────────────────────────────────────────────────────
const COLORS = {
  accent:      [99,  102, 241],  // indigo-500
  accentLight: [224, 231, 255],  // indigo-100
  black:       [15,  15,  15],
  dark:        [30,  30,  30],
  heading:     [17,  24,  39],
  body:        [55,  65,  81],
  muted:       [107, 114, 128],
  border:      [229, 231, 235],
  white:       [255, 255, 255],
  codeBg:      [15,  23,  42],
  codeText:    [226, 232, 240],
};

// ── Constants ─────────────────────────────────────────────────────────────────
const PAGE_W  = 210;  // A4 mm
const PAGE_H  = 297;
const MARGIN  = 20;
const CONTENT_W = PAGE_W - MARGIN * 2;
const LINE_H_BODY = 6;
const LINE_H_SM   = 5;

// ── Helpers ───────────────────────────────────────────────────────────────────
function rgbArr(arr) { return `rgb(${arr.join(",")})`; }

function setColor(doc, arr, which = "fill") {
  if (which === "fill") doc.setFillColor(...arr);
  else doc.setDrawColor(...arr);
}

function setTextColor(doc, arr) { doc.setTextColor(...arr); }

// Wrap text and return array of lines
function wrapText(doc, text, maxW) {
  return doc.splitTextToSize(text, maxW);
}

// Check if we need a new page and add one if so
function checkNewPage(doc, y, needed = LINE_H_BODY, pageNum, totalPages) {
  if (y + needed > PAGE_H - 20) {
    doc.addPage();
    pageNum[0]++;
    drawPageFooter(doc, pageNum[0], totalPages);
    return MARGIN + 10;
  }
  return y;
}

// ── Header ────────────────────────────────────────────────────────────────────
function drawPageHeader(doc, title, subtitle) {
  // Full-width accent bar
  setColor(doc, COLORS.accent, "fill");
  doc.rect(0, 0, PAGE_W, 14, "F");

  // Logo / brand text
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  setTextColor(doc, COLORS.white);
  doc.text("⭐ StarNote AI", MARGIN, 9);

  // Date / subtitle top right
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  const now = new Date().toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" });
  doc.text(now, PAGE_W - MARGIN, 9, { align: "right" });

  // Title block below bar
  let y = 24;
  if (title) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    setTextColor(doc, COLORS.heading);
    const lines = wrapText(doc, title, CONTENT_W);
    doc.text(lines, MARGIN, y);
    y += lines.length * 7 + 2;
  }

  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    setTextColor(doc, COLORS.muted);
    doc.text(subtitle, MARGIN, y);
    y += 8;
  }

  // Divider
  setColor(doc, COLORS.border, "draw");
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  return y + 6;
}

// ── Footer ────────────────────────────────────────────────────────────────────
function drawPageFooter(doc, pageNum, totalPages) {
  const y = PAGE_H - 10;
  setColor(doc, COLORS.border, "draw");
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y - 3, PAGE_W - MARGIN, y - 3);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  setTextColor(doc, COLORS.muted);
  doc.text("Generated by StarNote AI", MARGIN, y);
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_W - MARGIN, y, { align: "right" });
}

// ── Markdown parser & renderer ────────────────────────────────────────────────
// Parse raw markdown into simple token objects for rendering
function parseMarkdown(md) {
  const lines = md.split("\n");
  const tokens = [];
  let inCode = false;
  let codeBlock = [];
  let codeLang = "";

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // Code block
    if (line.trimStart().startsWith("```")) {
      if (!inCode) {
        inCode = true;
        codeLang = line.replace(/```/, "").trim();
        codeBlock = [];
      } else {
        tokens.push({ type: "code", lang: codeLang, text: codeBlock.join("\n") });
        inCode = false;
        codeBlock = [];
        codeLang = "";
      }
      continue;
    }
    if (inCode) { codeBlock.push(line); continue; }

    // Headings
    if (/^### /.test(line)) { tokens.push({ type: "h3", text: line.replace(/^### /, "") }); continue; }
    if (/^## /.test(line))  { tokens.push({ type: "h2", text: line.replace(/^## /, "") }); continue; }
    if (/^# /.test(line))   { tokens.push({ type: "h1", text: line.replace(/^# /, "") }); continue; }

    // Horizontal rule
    if (/^---+$/.test(line.trim())) { tokens.push({ type: "hr" }); continue; }

    // Bullet list
    if (/^[-*] /.test(line))        { tokens.push({ type: "bullet", text: line.replace(/^[-*] /, ""), level: 0 }); continue; }
    if (/^  [-*] /.test(line))      { tokens.push({ type: "bullet", text: line.replace(/^  [-*] /, ""), level: 1 }); continue; }

    // Numbered list
    const numMatch = line.match(/^(\d+)\. (.*)/);
    if (numMatch) { tokens.push({ type: "numbered", num: numMatch[1], text: numMatch[2] }); continue; }

    // Blockquote
    if (/^> /.test(line)) { tokens.push({ type: "quote", text: line.replace(/^> /, "") }); continue; }

    // Emoji tip line (💡 **Key Takeaway**)
    if (/^💡/.test(line)) { tokens.push({ type: "tip", text: line.replace(/^💡\s*/, "") }); continue; }

    // Bold heading-like lines (##-equivalent with **)
    if (/^\*\*[^*]+\*\*$/.test(line.trim())) {
      tokens.push({ type: "bold", text: line.trim().replace(/\*\*/g, "") }); continue;
    }

    // Empty line
    if (line.trim() === "") { tokens.push({ type: "blank" }); continue; }

    // Default paragraph
    tokens.push({ type: "para", text: line });
  }
  return tokens;
}

// Strip inline markdown for plain text rendering
function stripInline(text) {
  return text
    .replace(/\*\*(.+?)\*\*/g, "$1")
    .replace(/\*(.+?)\*/g, "$1")
    .replace(/`(.+?)`/g, "$1")
    .replace(/\[(.+?)\]\(.+?\)/g, "$1");
}

// ── Render Tokens onto jsPDF doc ──────────────────────────────────────────────
function renderTokens(doc, tokens, startY, pageNum, estimatedTotal) {
  let y = startY;

  for (let i = 0; i < tokens.length; i++) {
    const t = tokens[i];

    switch (t.type) {
      case "blank":
        y += 3;
        break;

      case "hr":
        y = checkNewPage(doc, y, 6, pageNum, estimatedTotal);
        setColor(doc, COLORS.border, "draw");
        doc.setLineWidth(0.4);
        doc.line(MARGIN, y, PAGE_W - MARGIN, y);
        y += 6;
        break;

      case "h1": {
        y = checkNewPage(doc, y, 16, pageNum, estimatedTotal);
        y += 4;
        doc.setFont("helvetica", "bold");
        doc.setFontSize(16);
        setTextColor(doc, COLORS.heading);
        const lines = wrapText(doc, stripInline(t.text), CONTENT_W);
        doc.text(lines, MARGIN, y);
        y += lines.length * 7 + 2;
        // underline
        setColor(doc, COLORS.accent, "draw");
        doc.setLineWidth(0.8);
        doc.line(MARGIN, y - 1, MARGIN + 40, y - 1);
        y += 4;
        break;
      }

      case "h2": {
        y = checkNewPage(doc, y, 14, pageNum, estimatedTotal);
        y += 3;
        doc.setFont("helvetica", "bold");
        doc.setFontSize(13);
        setTextColor(doc, COLORS.heading);
        const lines = wrapText(doc, stripInline(t.text), CONTENT_W);
        doc.text(lines, MARGIN, y);
        y += lines.length * 6.5 + 4;
        break;
      }

      case "h3":
      case "bold": {
        y = checkNewPage(doc, y, 10, pageNum, estimatedTotal);
        y += 2;
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        setTextColor(doc, COLORS.body);
        const lines = wrapText(doc, stripInline(t.text), CONTENT_W);
        doc.text(lines, MARGIN, y);
        y += lines.length * 6 + 2;
        break;
      }

      case "para": {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        setTextColor(doc, COLORS.body);
        const lines = wrapText(doc, stripInline(t.text), CONTENT_W);
        for (const line of lines) {
          y = checkNewPage(doc, y, LINE_H_BODY, pageNum, estimatedTotal);
          doc.text(line, MARGIN, y);
          y += LINE_H_BODY;
        }
        break;
      }

      case "bullet": {
        const indent = MARGIN + (t.level || 0) * 8;
        const textW = CONTENT_W - ((t.level || 0) * 8) - 6;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        setTextColor(doc, COLORS.body);
        const lines = wrapText(doc, stripInline(t.text), textW);
        for (let li = 0; li < lines.length; li++) {
          y = checkNewPage(doc, y, LINE_H_BODY, pageNum, estimatedTotal);
          if (li === 0) {
            // Bullet dot
            setColor(doc, COLORS.accent, "fill");
            doc.circle(indent + 1.5, y - 1.5, 1.2, "F");
            doc.text(lines[li], indent + 5, y);
          } else {
            doc.text(lines[li], indent + 5, y);
          }
          y += LINE_H_BODY;
        }
        y += 1;
        break;
      }

      case "numbered": {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        setTextColor(doc, COLORS.body);
        const lines = wrapText(doc, stripInline(t.text), CONTENT_W - 10);
        for (let li = 0; li < lines.length; li++) {
          y = checkNewPage(doc, y, LINE_H_BODY, pageNum, estimatedTotal);
          if (li === 0) {
            doc.setFont("helvetica", "bold");
            setTextColor(doc, COLORS.accent);
            doc.text(`${t.num}.`, MARGIN, y);
            doc.setFont("helvetica", "normal");
            setTextColor(doc, COLORS.body);
            doc.text(lines[li], MARGIN + 8, y);
          } else {
            doc.text(lines[li], MARGIN + 8, y);
          }
          y += LINE_H_BODY;
        }
        y += 1;
        break;
      }

      case "quote": {
        y = checkNewPage(doc, y, 12, pageNum, estimatedTotal);
        // Accent bar on left
        setColor(doc, COLORS.accentLight, "fill");
        setColor(doc, COLORS.accent, "draw");
        doc.setLineWidth(0);
        const lines = wrapText(doc, stripInline(t.text), CONTENT_W - 10);
        const blockH = lines.length * LINE_H_SM + 8;
        doc.rect(MARGIN, y - 4, CONTENT_W, blockH, "F");
        setColor(doc, COLORS.accent, "fill");
        doc.rect(MARGIN, y - 4, 2.5, blockH, "F");

        doc.setFont("helvetica", "italic");
        doc.setFontSize(10);
        setTextColor(doc, COLORS.body);
        for (const line of lines) {
          doc.text(line, MARGIN + 7, y);
          y += LINE_H_SM;
        }
        y += 6;
        break;
      }

      case "code": {
        y = checkNewPage(doc, y, 20, pageNum, estimatedTotal);
        const codeLines = t.text.split("\n");
        const blockH = codeLines.length * 4.5 + 10;
        y = checkNewPage(doc, y, blockH, pageNum, estimatedTotal);

        // Dark background block
        setColor(doc, COLORS.codeBg, "fill");
        doc.rect(MARGIN, y - 4, CONTENT_W, blockH, "F");

        // Lang tag
        if (t.lang) {
          doc.setFont("helvetica", "bold");
          doc.setFontSize(7);
          setTextColor(doc, [99, 102, 241]);
          doc.text(t.lang.toUpperCase(), MARGIN + 3, y);
          y += 5;
        } else {
          y += 2;
        }

        doc.setFont("courier", "normal");
        doc.setFontSize(8);
        setTextColor(doc, COLORS.codeText);
        for (const cl of codeLines) {
          y = checkNewPage(doc, y, 4.5, pageNum, estimatedTotal);
          doc.text(cl || " ", MARGIN + 4, y);
          y += 4.5;
        }
        y += 6;
        break;
      }

      case "tip": {
        y = checkNewPage(doc, y, 16, pageNum, estimatedTotal);
        const lines = wrapText(doc, stripInline(t.text), CONTENT_W - 12);
        const blockH = lines.length * LINE_H_SM + 10;
        y = checkNewPage(doc, y, blockH, pageNum, estimatedTotal);

        // Soft accent background
        setColor(doc, [238, 242, 255], "fill");
        doc.rect(MARGIN, y - 5, CONTENT_W, blockH, "F");
        setColor(doc, COLORS.accent, "fill");
        doc.rect(MARGIN, y - 5, 2.5, blockH, "F");

        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        setTextColor(doc, COLORS.accent);
        doc.text("💡 Key Takeaway", MARGIN + 6, y);
        y += 5;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        setTextColor(doc, COLORS.body);
        for (const line of lines) {
          doc.text(line, MARGIN + 6, y);
          y += LINE_H_SM;
        }
        y += 6;
        break;
      }

      default:
        break;
    }
  }

  return y;
}

// ── Flashcards PDF ────────────────────────────────────────────────────────────
function renderFlashcardsPDF(doc, flashcards, pageNum, totalPages) {
  let y = MARGIN + 10;
  const cardW = CONTENT_W;
  const col1 = MARGIN;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  setTextColor(doc, COLORS.muted);
  doc.text(`${flashcards.length} Flashcards`, col1, y);
  y += 10;

  for (let i = 0; i < flashcards.length; i++) {
    const card = flashcards[i];
    const qLines = wrapText(doc, card.question || card.front || "", cardW - 10);
    const aLines = wrapText(doc, card.answer   || card.back  || "", cardW - 10);
    const cardH = qLines.length * 5 + aLines.length * 5 + 22;

    y = checkNewPage(doc, y, cardH + 4, pageNum, totalPages);

    // Card shadow-like border
    setColor(doc, COLORS.border, "fill");
    doc.rect(col1 + 1, y + 1, cardW, cardH, "F");

    // Card body
    setColor(doc, COLORS.white, "fill");
    setColor(doc, COLORS.border, "draw");
    doc.setLineWidth(0.4);
    doc.roundedRect(col1, y, cardW, cardH, 3, 3, "FD");

    // Card number badge
    setColor(doc, COLORS.accent, "fill");
    doc.roundedRect(col1 + 4, y + 4, 14, 6, 1.5, 1.5, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    setTextColor(doc, COLORS.white);
    doc.text(`#${i + 1}`, col1 + 11, y + 8.5, { align: "center" });

    // Question
    let cardY = y + 5;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    setTextColor(doc, COLORS.heading);
    for (const l of qLines) {
      doc.text(l, col1 + 22, cardY);
      cardY += 5;
    }

    // Divider
    cardY += 3;
    setColor(doc, COLORS.border, "draw");
    doc.setLineWidth(0.3);
    doc.line(col1 + 6, cardY, col1 + cardW - 6, cardY);
    cardY += 4;

    // Answer
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    setTextColor(doc, COLORS.body);
    for (const l of aLines) {
      doc.text(l, col1 + 6, cardY);
      cardY += 5;
    }

    y += cardH + 6;
  }
}

// ── Main export functions ─────────────────────────────────────────────────────

/**
 * Export an AI Artifact to PDF (markdown, flashcards, quiz, code, etc.)
 * @param {object} artifact - The artifact object { type, content, meta }
 * @param {string} title    - Optional title
 */
export async function exportArtifactToPDF(artifact, title = "StarNote AI Export") {
  const { type, content } = artifact;
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  // We'll do a two-pass: estimate pages, then render
  // Pass 1: figure out total pages (simplified: add 1 page, then count)
  const pageNum = [1];
  const totalPages = [1]; // placeholder, will update after render

  let y = drawPageHeader(doc, title, `${TYPE_LABELS[type] || "Document"} · ${new Date().toLocaleDateString()}`);
  drawPageFooter(doc, 1, "—");

  if (type === "flashcards") {
    // Parse flashcards using same logic as artifactDetector.parseFlashcards
    let cards = [];

    // Bold **Q: / **A: format
    const boldFormat = [...content.matchAll(/\*\*Q\d*[:.]\*?\*?\s*(.+?)\n+\*\*A\d*[:.]\*?\*?\s*([\s\S]+?)(?=\*\*Q|\n\n\n|$)/gi)];
    if (boldFormat.length > 0) {
      cards = boldFormat.map(m => ({ question: m[1].trim(), answer: m[2].trim() }));
    } else {
      // Numbered Q: / A: format
      const lines = content.split("\n").filter(Boolean);
      let current = null;
      for (const line of lines) {
        const qMatch = line.match(/^Q\d*[:.]\s*(.+)/i);
        const aMatch = line.match(/^A\d*[:.]\s*(.+)/i);
        if (qMatch) { current = { question: qMatch[1].trim(), answer: "" }; }
        else if (aMatch && current) {
          current.answer = aMatch[1].trim();
          cards.push(current);
          current = null;
        }
      }
    }

    if (cards.length > 0) {
      renderFlashcardsPDF(doc, cards, pageNum, totalPages[0]);
    } else {
      // Fallback: render as markdown
      const tokens = parseMarkdown(content);
      renderTokens(doc, tokens, y, pageNum, totalPages[0]);
    }

  } else {
    const tokens = parseMarkdown(content);
    renderTokens(doc, tokens, y, pageNum, totalPages[0]);
  }

  // Update total page count in footers
  const total = doc.getNumberOfPages();
  for (let p = 1; p <= total; p++) {
    doc.setPage(p);
    drawPageFooter(doc, p, total);
  }

  const filename = title.replace(/[^a-z0-9]/gi, "_").toLowerCase().slice(0, 40) + ".pdf";
  doc.save(filename);
}

const TYPE_LABELS = {
  markdown: "Document",
  flashcards: "Flashcards",
  quiz: "Quiz",
  code: "Code",
  table: "Table",
  "study-plan": "Study Plan",
  mermaid: "Diagram",
};

/**
 * Export a Notes/Reader page to PDF using html2canvas to capture the visual canvas
 * @param {React.RefObject} contentRef - Ref to the DOM element to capture
 * @param {string} title - Title of the note
 */
export async function exportNoteToPDF(contentRef, title = "My Note") {
  const element = contentRef?.current;
  if (!element) return;

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = 210;
  const pageH = 297;
  const margin = 14;

  // Capture the DOM element as a high-res canvas
  const canvas = await html2canvas(element, {
    scale: 2,
    useCORS: true,
    backgroundColor: "#ffffff",
    logging: false,
    scrollX: 0,
    scrollY: 0,
    windowWidth: element.scrollWidth,
    windowHeight: element.scrollHeight,
  });

  const imgData  = canvas.toDataURL("image/jpeg", 0.92);
  const imgW     = pageW - margin * 2;
  const imgH     = (canvas.height * imgW) / canvas.width;

  // Draw header on first page
  doc.setFillColor(...COLORS.accent);
  doc.rect(0, 0, pageW, 12, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(255, 255, 255);
  doc.text("⭐ StarNote AI", margin, 8);
  const now = new Date().toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" });
  doc.text(now, pageW - margin, 8, { align: "right" });

  // Title
  let y = 22;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...COLORS.heading);
  doc.text(title, margin, y);
  y += 10;

  // Divider
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageW - margin, y);
  y += 6;

  // Image: paginate if tall
  const contentH = pageH - y - 14;
  const totalPages = Math.ceil(imgH / contentH);

  for (let p = 0; p < totalPages; p++) {
    if (p > 0) {
      doc.addPage();
      y = 14;
    }

    // Clip and draw portion of image
    const sliceY = p * contentH;
    const sliceH = Math.min(contentH, imgH - sliceY);

    // Create a temporary canvas to slice the image
    const sliceCanvas = document.createElement("canvas");
    const ratio = canvas.width / imgW;
    sliceCanvas.width = canvas.width;
    sliceCanvas.height = sliceH * ratio;
    const sliceCtx = sliceCanvas.getContext("2d");
    sliceCtx.drawImage(canvas, 0, sliceY * ratio, canvas.width, sliceH * ratio, 0, 0, canvas.width, sliceH * ratio);

    const sliceData = sliceCanvas.toDataURL("image/jpeg", 0.92);
    doc.addImage(sliceData, "JPEG", margin, y, imgW, sliceH);

    // Footer
    const fY = pageH - 10;
    doc.setDrawColor(...COLORS.border);
    doc.setLineWidth(0.3);
    doc.line(margin, fY - 3, pageW - margin, fY - 3);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.muted);
    doc.text("Generated by StarNote AI", margin, fY);
    doc.text(`Page ${p + 1} of ${totalPages}`, pageW - margin, fY, { align: "right" });
  }

  const filename = title.replace(/[^a-z0-9]/gi, "_").toLowerCase().slice(0, 40) + ".pdf";
  doc.save(filename);
}
